Update ticks: 20
Apply physics: false
Apply lit physics: false

LightBlocks:
  anvtnt:
    hours:
      - 0
      - 500
      - 1000
      - 5000
    materials:
      - REDSTONE_LAMP
      - REDSTONE_LAMP LIT
      - ANVIL
      - TNT
  honoak:
    hours:
      - 1000
      - 6000
      - 15000
      - 0
    materials:
      - OAK_WOOD
      - SPRUCE_WOOD
      - ACACIA_WOOD
      - HONEY_BLOCK